### ISSUE TITLE
Détails trames 63 octets Connect

### ISSUE THREAD

**Issue by Gibs91** [Burnallover/frisquet-mqtt#1]
Format de la trame 63 octets Satellite (08h)  vers Chaudière (80h) à destination de Connect (7Eh):

| Dest| Src| Id |inc |Dest |Type |4 u8          |4 u8           |nb data        |Confort  |Réduit    |H.Gel  |Mode |00  |Dimanche  |Lundi  |Mardi |Mercredi         |Jeudi               | Vendredi          |Samedi|
|------|----|---|----|------|------|-----------|-------------|--------------|---------|----------|-------|--------|----|------------|------|---|----|----|----|---|
| 80  | 08  |1A |F8 | 7E  | 17    | A1540015 | A1540018  | 30 (48 datas) | 9B (20.5) | 7D (17.5) | 64 (15) | 0525 | 00 |0700E0FFFFFF |0300060080FF |0300060080FF |0300060080FF |0300060080FF |0300060080FF |0700E0FFFFFF |

**Comment by Gibs91** [comment]
Codage de la programmation hebdomadaire :

exemple Lundi : 6 octets par jour = 48bits => 0.5heure/bit  (ex: Confort 8h30-9h30 + 19h30-1h):

03 00 06 00 80 FF => Lecture de chaque mot en **LSB first** : 
|11000000 |00000000 |01100000 |00000000 |00000001 |11111111|
|-----------|------------|-----------|------------|-----------|----------|
|1h             |                 |8h30/9h30|               |       19h30|                |

**Comment by Burnallover** [comment]
Merci @Gibs91, c'est ajouté dans le wiki !
